/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarian;

import SQLServer.ConnectThanh;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;


public class Edit_Profile extends javax.swing.JFrame {

    
    private String mathe;
    private String hoten;
    private String SDT;
    private String Email;
    private String Diachi;
    
    public Edit_Profile(String mathe, String hoten, String SDT, String Email, String Diachi) {
        this.mathe = mathe;
        this.hoten  = hoten;
        this.SDT = SDT;
        this.Email = Email;
        this.Diachi = Diachi;
        initComponents();
        setData();
 
    }
    
    public void setData() {
        txtMathe.setText(mathe);
        txtHoten.setText(hoten);
        txtSĐT.setText(SDT);
        txtEmail.setText(Email);
        txtDiachi.setText(Diachi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        lblCSHS = new javax.swing.JLabel();
        lblMathe = new javax.swing.JLabel();
        txtMathe = new javax.swing.JTextField();
        lblHoten = new javax.swing.JLabel();
        txtHoten = new javax.swing.JTextField();
        lblSĐT = new javax.swing.JLabel();
        txtSĐT = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblDiachi = new javax.swing.JLabel();
        txtDiachi = new javax.swing.JTextField();
        lblGhichu = new javax.swing.JLabel();
        btnHoantat = new javax.swing.JButton();
        btnHuybo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LIBRARIAN");
        setResizable(false);

        main_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCSHS.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCSHS.setText("Chỉnh Sửa Hồ Sơ");

        lblMathe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMathe.setText("Mã Thẻ");

        txtMathe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblHoten.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblHoten.setText("Họ Tên");

        txtHoten.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblSĐT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSĐT.setText("SĐT");

        txtSĐT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblEmail.setText("Email");

        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblDiachi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDiachi.setText("Địa Chỉ");

        txtDiachi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblGhichu.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        lblGhichu.setForeground(new java.awt.Color(255, 0, 0));
        lblGhichu.setText("Kiểm tra kỹ thông tin trước khi chỉnh sửa");

        btnHoantat.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnHoantat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/document.png"))); // NOI18N
        btnHoantat.setText("Hoàn tất");
        btnHoantat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoantatActionPerformed(evt);
            }
        });

        btnHuybo.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnHuybo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnHuybo.setText("Hủy bỏ");
        btnHuybo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(lblCSHS, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMathe, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSĐT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMathe)
                                .addComponent(txtHoten)
                                .addComponent(txtSĐT, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lblGhichu, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnHoantat, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addComponent(btnHuybo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCSHS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMathe, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMathe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSĐT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSĐT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblGhichu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHoantat)
                    .addComponent(btnHuybo))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyboActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnHuyboActionPerformed

    private void btnHoantatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoantatActionPerformed
        if(txtMathe.getText().equals("") || txtHoten.getText().equals("") || txtSĐT.getText().equals("")
                || txtEmail.getText().equals("") || txtDiachi.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Tất cả các trường không được để trống !!!", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
        else{
            //Cập nhật csdl
            String Mathe_tmp = txtMathe.getText();
            String Hoten_tmp = txtHoten.getText();
            String SDT_tmp = txtSĐT.getText();
            String Email_tmp = txtEmail.getText();
            String DiaChi_tmp = txtDiachi.getText();
            
            int so_ma = Integer.parseInt(Mathe_tmp);
            
            try{
                Statement s = ConnectThanh.Connection().createStatement();
                s.execute("Update Nguoidung set ID =" + so_ma + ",HoTen ='" + Hoten_tmp + "',SĐT ='" + SDT_tmp
                            + "',Email ='" + Email_tmp + "',Diachi='" + DiaChi_tmp + "' where ID = " + Integer.parseInt(mathe));
                JOptionPane.showMessageDialog(this, "Cập nhật hoàn thành", "THÔNG BÁO", JOptionPane.DEFAULT_OPTION);
                //Gọi lại Profile
                this.setVisible(false);
                Show_Profile p = new Show_Profile(txtMathe.getText());
                p.setVisible(true);
                p.setLocationRelativeTo(null);
                
                ConnectThanh.Connection().close();
            }catch(Exception e){
                e.printStackTrace();
            }
            
            
        }
        
        
    }//GEN-LAST:event_btnHoantatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHoantat;
    private javax.swing.JButton btnHuybo;
    private javax.swing.JLabel lblCSHS;
    private javax.swing.JLabel lblDiachi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGhichu;
    private javax.swing.JLabel lblHoten;
    private javax.swing.JLabel lblMathe;
    private javax.swing.JLabel lblSĐT;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtMathe;
    private javax.swing.JTextField txtSĐT;
    // End of variables declaration//GEN-END:variables
}
