/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarian;

import SQLServer.ConnectThanh;
import entities.Publications;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.lang.Object;
/**
 *
 * @author thanh
 */
public class List_Publications extends javax.swing.JFrame {
//    private ArrayList <Publications> list;
//    DefaultTableModel model;
    /**
     * Creates new form List_Publication
     */
    public List_Publications() {
        initComponents();
        setLocationRelativeTo(null);  
        try {   
            Connection conn = ConnectThanh.Connection();
            PreparedStatement ps = conn.prepareStatement("Select * From AnPham");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel) DanhSachAnPhamTb.getModel();
            while(rs.next()){
               Object objlist[] ={
                   rs.getString("maAP"), rs.getString("tenAP"), rs.getString("Theloai"), rs.getString("Tacgia"),
               rs.getString("Phuthu"), rs.getString("soluong"), rs.getString("pathing"), rs.getString("hienco")};
               model.addRow(objlist);
//                P = new Publications(rs.getString("maAP"), rs.getString("tenAP"), rs.getString("Theloai"), rs.getString("Tacgia"),
//               rs.getString("Phuthu"), rs.getString("soluong"), rs.getString("pathing"), rs.getString("hienco"));
//                list.add(P);
            }
        } catch (Exception e) {
            e.printStackTrace();        
    }
    }
    
    
//    public ArrayList<Publications> getPublications(){
//            ArrayList<Publications> list = new ArrayList<>();
//            String sql = "Select * From AnPham;";
//         try {   
//            Connection conn = ConnectThanh.Connection();
//            PreparedStatement ps = conn.prepareStatement(sql);
//            ResultSet rs = ps.executeQuery();
//            Publications P;
//            while(rs.next()){
////                Publications P = new Publications();
//                P = new Publications(rs.getString("maAP"), rs.getString("tenAP"), rs.getString("Theloai"), rs.getString("Tacgia"),
//               rs.getString("Phuthu"), rs.getString("soluong"), rs.getString("pathing"), rs.getString("hienco"));
//                list.add(P);
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//    }
//         return list;
//    }
//    
//    public void show_Publications(){
//        ArrayList<Publications> list = getPublications();
//        DefaultTableModel model = (DefaultTableModel) DanhSachAnPhamTb.getModel();
//        Object[] row = new Object[7];
//        for(int i=0;i<list.size();i++){
//            row[0] = list.get(i).getMaAP();
//            row[1] = list.get(i).getTenAP();
//            row[2] = list.get(i).getTheloai();
//            row[3] = list.get(i).getTacgia();
//            row[4] = list.get(i).getPhuthu();
//            row[5] = list.get(i).getHienco();
//            model.addRow(row);
//        }
//          list = new List_Publications().getPublications();
//        model = (DefaultTableModel) DanhSachAnPhamTb.getModel();
//        
//        model.setColumnIdentifiers(new Object[]{
//            "maAP","tenAP","Theloai","Tacgia","Phuthu","hienco"
//        });
//        int i = 0;
//        for(Publications P :list){
//            model.addRow(new Object[]{
//                i++, P.getMaAP(), P.getTenAP(), P.getTacgia(), P.getTheloai(), P.getSoluong(), P.getPhuthu()
//            });
//        }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ThemmoiBt = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DanhSachAnPhamTb = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ThemmoiBt.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        ThemmoiBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/book.png"))); // NOI18N
        ThemmoiBt.setText("Thêm Mới");
        ThemmoiBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemmoiBtActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/book (1).png"))); // NOI18N
        btnSearch.setText("Tìm Kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        DanhSachAnPhamTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Ấn Phẩm", "Tên Ấn Phẩm", "Thể Loại", "Tác giả", "Phụ Thu", "Số lượng", "Pathing", "Hiện có"
            }
        ));
        jScrollPane1.setViewportView(DanhSachAnPhamTb);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Danh sách ấn phẩm");

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(398, 398, 398)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(ThemmoiBt)
                .addGap(84, 84, 84)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ThemmoiBt)
                        .addComponent(btnSearch))
                    .addComponent(btnExit))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThemmoiBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemmoiBtActionPerformed
        this.setVisible(false);
        Add_Publications ap = new  Add_Publications();
        ap.setVisible(true);
        ap.setLocationRelativeTo(null);
    }//GEN-LAST:event_ThemmoiBtActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        Search_Publications Sp = new  Search_Publications();
        Sp.setVisible(true);
        Sp.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(List_Publications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(List_Publications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(List_Publications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(List_Publications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new List_Publications().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DanhSachAnPhamTb;
    private javax.swing.JButton ThemmoiBt;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
