/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarian;

import XuLyAnh.Edit_Img;
import javax.swing.ImageIcon;


/**
 *
 * @author thanh
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logolb = new javax.swing.JLabel();
        ContentLb = new javax.swing.JLabel();
        JPanelDesign = new javax.swing.JPanel();
        HoSobt = new javax.swing.JToggleButton();
        DanhSachbt = new javax.swing.JToggleButton();
        LichSubt = new javax.swing.JToggleButton();
        LichSujb = new javax.swing.JLabel();
        HoSojb = new javax.swing.JLabel();
        Danhsachjb = new javax.swing.JLabel();
        ExitBt = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Logolb.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                LogolbAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        ContentLb.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        ContentLb.setText("LIBRARIAN");

        JPanelDesign.setBackground(new java.awt.Color(0, 204, 204));
        JPanelDesign.setPreferredSize(new java.awt.Dimension(598, 3));

        javax.swing.GroupLayout JPanelDesignLayout = new javax.swing.GroupLayout(JPanelDesign);
        JPanelDesign.setLayout(JPanelDesignLayout);
        JPanelDesignLayout.setHorizontalGroup(
            JPanelDesignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        JPanelDesignLayout.setVerticalGroup(
            JPanelDesignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        HoSobt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/profile_1.png"))); // NOI18N
        HoSobt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoSobtActionPerformed(evt);
            }
        });

        DanhSachbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/list.png"))); // NOI18N
        DanhSachbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DanhSachbtActionPerformed(evt);
            }
        });

        LichSubt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/agreement.png"))); // NOI18N
        LichSubt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LichSubtActionPerformed(evt);
            }
        });

        LichSujb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LichSujb.setText("Giao dịch");

        HoSojb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        HoSojb.setText("Hồ Sơ");

        Danhsachjb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Danhsachjb.setText("Danh Sách");

        ExitBt.setForeground(new java.awt.Color(255, 255, 255));
        ExitBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit_1.png"))); // NOI18N
        ExitBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 95, Short.MAX_VALUE)
                .addComponent(Logolb, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(ContentLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelDesign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Danhsachjb)
                        .addGap(226, 226, 226)
                        .addComponent(HoSojb)
                        .addGap(240, 240, 240)
                        .addComponent(LichSujb)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(DanhSachbt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(HoSobt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(LichSubt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ExitBt)
                        .addGap(71, 71, 71))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Logolb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ContentLb, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(JPanelDesign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoSobt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LichSubt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DanhSachbt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LichSujb)
                    .addComponent(HoSojb)
                    .addComponent(Danhsachjb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(ExitBt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogolbAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_LogolbAncestorAdded
        ImageIcon icon = Edit_Img.Edit_Img("X:\\Image-Login-menu\\bookshelf-icon.png",Logolb );
        Logolb.setIcon(icon);
    }//GEN-LAST:event_LogolbAncestorAdded

    private void HoSobtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoSobtActionPerformed
        Search_Profile Hs = new Search_Profile();
        Hs.setVisible(true);
//        Hs.setLocationRelativeTo(null);
    }//GEN-LAST:event_HoSobtActionPerformed

    private void DanhSachbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DanhSachbtActionPerformed
        List_Publications LP = new List_Publications();
        LP.setVisible(true);
//        LP.setLocationRelativeTo(null);
    }//GEN-LAST:event_DanhSachbtActionPerformed

    private void LichSubtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LichSubtActionPerformed
        this.setVisible(false);
        Deal d = new Deal();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
    }//GEN-LAST:event_LichSubtActionPerformed

    private void ExitBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtActionPerformed
        this.setVisible(false);
        Login Exit = new Login();
        Exit.setVisible(true);
        Exit.setLocationRelativeTo(null);
    }//GEN-LAST:event_ExitBtActionPerformed

    /**
     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                //new Menu().setVisible(true);
//                Menu menu = new Menu();
//                menu.setVisible(true);
//                menu.setLocationRelativeTo(null);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContentLb;
    private javax.swing.JToggleButton DanhSachbt;
    private javax.swing.JLabel Danhsachjb;
    private javax.swing.JToggleButton ExitBt;
    private javax.swing.JToggleButton HoSobt;
    private javax.swing.JLabel HoSojb;
    private javax.swing.JPanel JPanelDesign;
    private javax.swing.JToggleButton LichSubt;
    private javax.swing.JLabel LichSujb;
    private javax.swing.JLabel Logolb;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
