/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarian;


import SQLServer.ConnectThanh;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class Search_Publications extends javax.swing.JFrame {

    /**
     * Creates new form Search_Publications
     */
    public Search_Publications() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMaAP = new javax.swing.JLabel();
        txtMaAP = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblTenAP = new javax.swing.JLabel();
        txtTenAP = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LIBRARIAN");
        setResizable(false);

        lblMaAP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMaAP.setText("Mã Ấn Phẩm");

        txtMaAP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMaAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaAPActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/book (1).png"))); // NOI18N
        btnSearch.setText("Tìm Kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblTenAP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblTenAP.setText("Tên Ấn Phẩm");

        txtTenAP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaAP)
                    .addComponent(lblTenAP))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMaAP, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenAP, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearch)
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaAP)
                    .addComponent(txtMaAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenAP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnSearch)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if(txtMaAP.getText().equals("") || txtTenAP.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Mã Ấn Phẩm hoặc Tên Ấn Phẩm không đc để trống", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
        else{
            String maap = txtMaAP.getText();
            String tenap = txtTenAP.getText();
            String tmp = null;
        
            try {
                Statement s  = ConnectThanh.Connection().createStatement();
                ResultSet rs = s.executeQuery("select tenAP from AnPham where maAP = '" + maap + "';");
                while(rs.next()){
                    tmp = rs.getString("tenAP");
                }
                if(tenap.equals(tmp)){
                    this.setVisible(false);
                    Publications p = new Publications(txtMaAP.getText());
                    p.setVisible(true);
                }
                else
                    JOptionPane.showMessageDialog(this, "Ấn Phẩm " + tenap + " không tồn tại", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
                
                ConnectThanh.Connection().close();
            }catch(Exception e){
                e.printStackTrace();
            }
            
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtMaAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaAPActionPerformed
       try {
            String maAP = txtMaAP.getText();
            java.sql.Statement s = ConnectThanh.Connection().createStatement();
            ResultSet rs = s.executeQuery("select tenAP from AnPham where maAP ='" + maAP + "'; ");
            while ( rs.next() ) {
                txtTenAP.setText(rs.getString("tenAP"));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_txtMaAPActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Search_Publications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Search_Publications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Search_Publications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Search_Publications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Search_Publications().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel lblMaAP;
    private javax.swing.JLabel lblTenAP;
    private javax.swing.JTextField txtMaAP;
    private javax.swing.JTextField txtTenAP;
    // End of variables declaration//GEN-END:variables
}
