/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarian;


import SQLServer.ConnectThanh;
import XuLyAnh.Edit_Img;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ADMIN
 */
public class Update_Publications extends javax.swing.JFrame {

    private String maap;
    private String tenap;
    private String theloai;
    private String tacgia;
    private String soluong;
    private String conlai;
    private String phuthu;
    private String pathImg;
    private String pathImg_tmp;
    
    public Update_Publications(String maap, String tenap, String theloai, String tacgia, String soluong, String conlai, String phuthu, String path) {
        this.maap = maap;
        this.tenap = tenap;
        this.theloai = theloai;
        this.tacgia = tacgia;
        this.soluong = soluong;
        this.conlai = conlai;
        this.phuthu = phuthu;
        this.pathImg = path;
        pathImg_tmp = pathImg;
        initComponents();
        setData();
        setTheLoai();
    }

    public void setData(){
        txtMaAP.setText(maap);
        txtTenAP.setText(tenap);
        txtTacgia.setText(tacgia);
        txtPhuthu.setText(phuthu);
        txtSoluong.setText(soluong);
        txtConlai.setText(conlai);
        ImageIcon icon = Edit_Img.Edit_Img(pathImg, lblAnh);
        lblAnh.setIcon(icon);
        
    }
    
    public void setTheLoai(){
        try{
            Statement s = ConnectThanh.Connection().createStatement();
            ResultSet rs = s.executeQuery("select * from Theloai");
            while(rs.next()){
                ComboTheloai.addItem(rs.getString("TheLoai"));
            }
            
            ConnectThanh.Connection().close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        maanpham = new javax.swing.JLabel();
        tenanpham = new javax.swing.JLabel();
        TheLoai = new javax.swing.JLabel();
        TacGia = new javax.swing.JLabel();
        PhuThu = new javax.swing.JLabel();
        SoLuong = new javax.swing.JLabel();
        hinhanh = new javax.swing.JLabel();
        txtMaAP = new javax.swing.JTextField();
        txtTenAP = new javax.swing.JTextField();
        ComboTheloai = new javax.swing.JComboBox<>();
        txtTacgia = new javax.swing.JTextField();
        txtPhuthu = new javax.swing.JTextField();
        txtSoluong = new javax.swing.JTextField();
        btnHoantat = new javax.swing.JButton();
        btnHuybo = new javax.swing.JButton();
        btnLoadImg = new javax.swing.JButton();
        lblAnh = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtConlai = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LIBRARIAN");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblHeading.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(102, 102, 255));
        lblHeading.setText("Cập Nhật Ấn Phẩm");

        maanpham.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        maanpham.setText("Mã Ấn Phẩm");

        tenanpham.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tenanpham.setText("Tên ấn phẩm");

        TheLoai.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TheLoai.setText("Thể loại");

        TacGia.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TacGia.setText("Tác giả");

        PhuThu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PhuThu.setText("Phụ thu(VND/Ngay)");

        SoLuong.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SoLuong.setText("Số lượng");

        hinhanh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        hinhanh.setText("Hình ảnh");

        txtMaAP.setEnabled(false);
        txtMaAP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtTenAP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        ComboTheloai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtTacgia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtPhuthu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtSoluong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnHoantat.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnHoantat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/checked.png"))); // NOI18N
        btnHoantat.setText("Hoàn tất");
        btnHoantat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoantatActionPerformed(evt);
            }
        });

        btnHuybo.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnHuybo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnHuybo.setText("Hủy bỏ");
        btnHuybo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyboActionPerformed(evt);
            }
        });

        btnLoadImg.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnLoadImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btnLoadImg.setText("Chọn ảnh");
        btnLoadImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadImgActionPerformed(evt);
            }
        });

        lblAnh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Còn lại");

        txtConlai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(maanpham, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(tenanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenAP)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMaAP, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ComboTheloai, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtTacgia)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(PhuThu)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPhuthu, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(hinhanh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                            .addComponent(SoLuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnHoantat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtConlai)
                                            .addComponent(txtSoluong)
                                            .addComponent(btnLoadImg, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuybo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tenanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboTheloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhuThu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhuthu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConlai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hinhanh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoadImg, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHoantat)
                    .addComponent(btnHuybo))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyboActionPerformed
        this.setVisible(false);
        
    }//GEN-LAST:event_btnHuyboActionPerformed


    
    private void btnLoadImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadImgActionPerformed
        
        JFileChooser filechooser = new JFileChooser();
        //Lọc ra chỉ hiển thị file .jpg và .png
        FileNameExtensionFilter imgFilter = new FileNameExtensionFilter("Hinh Anh", "jpg", "png");
        
        filechooser.setFileFilter(imgFilter);
        //chỉ chọn 1 file tại 1 thoi diem, true thi chon nhieu file tại 1 thoi diem
        filechooser.setMultiSelectionEnabled(false);
        //hien thi dialog de chon file
        int n = filechooser.showDialog(this, "Chọn Ảnh");
        if(n == JFileChooser.APPROVE_OPTION){ // đã chon file
            File f = filechooser.getSelectedFile();
            //Lay duong dan file
            pathImg_tmp = f.getAbsolutePath();
 //           pathImg = f.getAbsolutePath().replace("//", "---="); // Dùng khi đường dẫn có kí tự đặc biệt
            //Dieu chinh kich thuoc a
            ImageIcon icon = Edit_Img.Edit_Img(pathImg_tmp, lblAnh);
            lblAnh.setIcon(icon);
            
        }
    }//GEN-LAST:event_btnLoadImgActionPerformed

    private void btnHoantatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoantatActionPerformed
        try {
            String tl = (String)ComboTheloai.getSelectedItem();
            Statement s = ConnectThanh.Connection().createStatement();
            if(tenap.equals(txtTenAP.getText()) == false)
                s.execute("Update AnPham set tenAP = '" + txtTenAP.getText() + "' where maAP = '" + maap + "';");
            if(theloai.equals(tl) == false)
                s.execute("Update AnPham set Theloai = '" + tl + "' where maAP = '" + maap + "';");
            if(tacgia.equals(txtTacgia.getText()) == false)
                s.execute("Update AnPham set Tacgia = '" + txtTacgia.getText() + "' where maAP = '" + maap + "';");
            if(phuthu.equals(txtPhuthu.getText())== false)
                s.execute("Update AnPham set PhuThu = '" + txtPhuthu.getText() + "' where maAP = '" + maap + "';");
            if(soluong.equals(txtSoluong.getText())== false)
                s.execute("Update AnPham set soLuong = '" + txtSoluong.getText() + "' where maAP = '" + maap + "';");
            if(conlai.equals(txtConlai.getText())== false)
                s.execute("Update AnPham set henCo = '" + txtConlai.getText() + "' where maAP = '" + maap + "';");
            if(pathImg.equals(pathImg_tmp)== false)
                s.execute("Update AnPham set pathing = '" + pathImg_tmp + "' where maAP = '" + maap + "';");
            
            ConnectThanh.Connection().close();

        }catch(Exception e){
            e.printStackTrace();
        }
        
        JOptionPane.showMessageDialog(this, "Đã cập nhật thành công", "THÔNG BÁO", JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
    }//GEN-LAST:event_btnHoantatActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboTheloai;
    private javax.swing.JLabel PhuThu;
    private javax.swing.JLabel SoLuong;
    private javax.swing.JLabel TacGia;
    private javax.swing.JLabel TheLoai;
    private javax.swing.JButton btnHoantat;
    private javax.swing.JButton btnHuybo;
    private javax.swing.JButton btnLoadImg;
    private javax.swing.JLabel hinhanh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel maanpham;
    private javax.swing.JLabel tenanpham;
    private javax.swing.JTextField txtConlai;
    private javax.swing.JTextField txtMaAP;
    private javax.swing.JTextField txtPhuthu;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTacgia;
    private javax.swing.JTextField txtTenAP;
    // End of variables declaration//GEN-END:variables
}
